<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Minimalist Layout</title>
    <style>
        * { box-sizing: border-box; font-family: 'Open Sans', Arial, sans-serif; }
        @page { size: A5 landscape; margin: 0; }
        body { margin: 0; background: #fff; display: flex; justify-content: center; align-items: flex-start; }
        .sheet { width: 210mm; height: 148mm; padding: 15mm; display: flex; flex-direction: column; margin: 0 auto;}
        .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 15mm; }
        .logo-text { font-size: 20pt; font-weight: 800; color: #111; letter-spacing: -1px; }
        .sub-text { color: #666; font-size: 9pt; margin-top: 2mm; }
        .record-id { text-align: right; font-size: 28pt; font-weight: 300; color: #ddd; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8mm; flex: 1; }
        .data-block { margin-bottom: 6mm; }
        .label { font-size: 8pt; text-transform: uppercase; color: #999; letter-spacing: 1px; font-weight: 600; margin-bottom: 1mm; }
        .value { font-size: 13pt; color: #222; font-weight: 500; }
        .weights-section { margin-top: 10mm; display: flex; justify-content: space-between; border-top: 1px solid #000; padding-top: 5mm; }
        .flex-block { text-align: left; }
        .flex-block.net { color: #111; font-weight: 700; transform: scale(1.1); transform-origin: left;}
        .footer { display: flex; justify-content: space-between; align-items: center; margin-top: 8mm; }
    </style>
</head>
<body>
    <div class="sheet">
        <div class="header">
            <div>
                <div class="logo-text">AL HAMAD KANTA</div>
                <div class="sub-text">Hafizabad Road, Vanike Tarar</div>
            </div>
            <div class="record-id">
                #{{ $record->id }}
            </div>
        </div>

        <div class="grid">
            <div>
                <div class="data-block">
                    <div class="label">Customer</div>
                    <div class="value">{{ $record->party }}</div>
                </div>
                <div class="data-block">
                    <div class="label">Vehicle No</div>
                    <div class="value">{{ $record->vehicle_number }}</div>
                </div>
                <div class="data-block">
                    <div class="label">Material Details</div>
                    <div class="value">{{ $record->description ?: 'No details provided' }}</div>
                </div>
            </div>
            <div>
                <div class="data-block">
                    <div class="label">Time In</div>
                    <div class="value">{{ $record->first_date }}</div>
                </div>
                <div class="data-block">
                    <div class="label">Time Out</div>
                    <div class="value">{{ $record->second_date ?: 'Pending' }}</div>
                </div>
                <div class="data-block">
                    <div class="label">Amount Paid</div>
                    <div class="value">PKR {{ number_format((float)$record->amount, 2) }}</div>
                </div>
            </div>
        </div>

        <div class="weights-section">
            <div class="flex-block">
                <div class="label">First Weight</div>
                <div class="value">{{ $record->first_weight }} KG</div>
            </div>
            <div class="flex-block">
                <div class="label">Second Weight</div>
                <div class="value">{{ $record->second_weight ?: 'TBA' }} KG</div>
            </div>
            <div class="flex-block net">
                <div class="label" style="color:#000;">Net Weight</div>
                <div class="value">{{ $record->net_weight ?: 'TBA' }} KG</div>
            </div>
        </div>
        
        <div class="footer">
            <div style="font-size: 8pt; color: #999;">Generated by operator {{ $user->phone ?? 'SYS' }}</div>
            <div>{!! $qrCode !!}</div>
        </div>
    </div>

@if(!isset($isPreview) || !$isPreview)
    <script>
        window.onload = function() { window.print(); }
        window.addEventListener("afterprint", function() { window.history.back(); });
    </script>
@endif
</body>
</html>
